import { renderDiscordMarkdown } from "@/lib/markdown/discord";
import { cn } from "@/lib/utils";

/**
 * Renders the same markdown Discord will get, through the same renderer the
 * admin previewed it with. The HTML is generated by us from a restricted
 * grammar — no user HTML ever survives `renderDiscordMarkdown`.
 */
export function DiscordMarkdown({
  markdown,
  className,
}: {
  markdown: string;
  className?: string;
}) {
  return (
    <div
      className={cn("md-body", className)}
      dangerouslySetInnerHTML={{ __html: renderDiscordMarkdown(markdown) }}
    />
  );
}
